//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int OrderId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int UserProfileId { get; set; }
        public int RestaurantId { get; set; }
        public int OrderStateId { get; set; }
        public int OrderTypeId { get; set; }
        public Nullable<System.DateTime> ScheduledDelivery { get; set; }
        public Nullable<float> DeliveryPrice { get; set; }
        public Nullable<bool> BookTable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
